config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "larps#index"

  resources :goals

  resources :larps do
    resources :characters
    resources :items
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :larp
  has_many :goal
  has_many :items

end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :character
  has_one :character

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :larp

end

app/models/larp.rb
class Larp < ApplicationRecord
  has_many :items
  has_many :characters

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character_and_larp, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @larp = Larp.find(params['larp_id'])
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @larp = Larp.find(params['larp_id'])
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)
    @larp = Larp.find(params['larp_id'])
    @character.larp = @larp

    if @character.save
      redirect_to larp_characters_path(@larp), notice: 'Character was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    if @character.update(character_params)
      redirect_to larp_characters_path(@larp), notice: 'Character was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    redirect_to larps_characters_path(@larp), notice: 'Character was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_character_and_larp
    @character = Character.find(params[:id])
    @larp = Larp.find(params['larp_id'])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def character_params
    params.fetch(:character, {}).permit(:name, :short_description)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.fetch(:goal, {})
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item_and_larp, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @larp = Larp.find(params['larp_id'])
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @larp = Larp.find(params['larp_id'])
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @larp = Larp.find(params['larp_id'])
    @item.larp = @larp
    if @item.save
      redirect_to larp_items_path(@larp), notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    if @item.update(item_params)
      redirect_to larp_items_path(@larp), notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_and_larp
      @item = Item.find(params[:id])
      @larp = Larp.find(params['larp_id'])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.fetch(:item, {}).permit(:name, :short_description)
    end
end

app/controllers/larps_controller.rb
class LarpsController < ApplicationController
  before_action :set_larp, only: [:show, :edit, :update, :destroy]

  # GET /larps
  # GET /larps.json
  def index
    @larps = Larp.all
  end

  # GET /larps/1
  # GET /larps/1.json
  def show
  end

  # GET /larps/new
  def new
    @larp = Larp.new
  end

  # GET /larps/1/edit
  def edit
  end

  # POST /larps
  # POST /larps.json
  def create
    @larp = Larp.new(larp_params)

    respond_to do |format|
      if @larp.save
        format.html { redirect_to @larp, notice: 'Larp was successfully created.' }
        format.json { render :show, status: :created, location: @larp }
      else
        format.html { render :new }
        format.json { render json: @larp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /larps/1
  # PATCH/PUT /larps/1.json
  def update
    respond_to do |format|
      if @larp.update(larp_params)
        format.html { redirect_to @larp, notice: 'Larp was successfully updated.' }
        format.json { render :show, status: :ok, location: @larp }
      else
        format.html { render :edit }
        format.json { render json: @larp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /larps/1
  # DELETE /larps/1.json
  def destroy
    @larp.destroy
    respond_to do |format|
      format.html { redirect_to larps_url, notice: 'Larp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_larp
      @larp = Larp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def larp_params
      params.fetch(:larp, {})
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/larps_helper.rb
module LarpsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/characters/_form.html.erb
<%= form_for([larp, character]) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= label_tag(:name) %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= label_tag(:short_description) %>
    <%= form.text_field :short_description %>
  </p>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character, larp: @larp %>

<%= link_to 'Back', larp_character_path(@larp, @character) %>

app/views/characters/index.html.erb
<h1>Characters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.short_description %></td>
        <td><%= link_to 'Show', larp_character_path(@larp, character) %></td>
        <td><%= link_to 'Edit', edit_larp_character_path(@larp, character) %></td>
        <td><%#= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_larp_character_path(@larp) %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character, larp: @larp %>

<%= link_to 'Back', larp_characters_path(@larp) %>

app/views/characters/show.html.erb
<h3> Title: <%= @character.name %> </h3>

<p> Description: <%= @character.short_description %> </p>

<%= link_to 'Edit', edit_larp_character_path(@larp, @character) %> |
<%= link_to 'Back', larp_characters_path(@larp) %>

app/views/goals/_form.html.erb
<%= form_with(model: goal, local: true) do |form| %>
  <% if goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<h1>Goals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.name %></td>
        <td><%= goal.short_description %></td>
        <td><%= link_to 'Show', goal %></td>
        <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
        <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal', new_goal_path %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<h3> Title: <%= @goal.name %> </h3>

<p> Description: <%= @goal.short_description %> </p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>

app/views/items/_form.html.erb
<%= form_for([larp, item]) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= label_tag(:name) %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= label_tag(:short_description) %>
    <%= form.text_field :short_description %>
  </p>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item, larp: @larp  %>

<%= link_to 'Show', larp_item_path(@larp, @item) %> |
<%= link_to 'Back', larp_items_path(@larp) %>

app/views/items/index.html.erb
<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.short_description %></td>
        <td><%= link_to 'Show', larp_item_path(@larp, item) %></td>
        <td><%= link_to 'Edit', edit_larp_item_path(@larp, item) %></td>
        <td><%#= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_larp_item_path(@larp) %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item, larp: @larp%>

<%= link_to 'Back', larp_items_path(@larp, @item) %>

app/views/items/show.html.erb
<h3> Title: <%= @item.name %> </h3>

<p> Description: <%= @item.short_description %> </p>

<%= link_to 'Edit', edit_larp_item_path(@larp, @item) %> |
<%= link_to 'Back', larp_items_path(@larp) %>

app/views/larps/_form.html.erb
<%= form_with(model: larp, local: true) do |form| %>
  <% if larp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(larp.errors.count, "error") %> prohibited this larp from being saved:</h2>

      <ul>
      <% larp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/larps/edit.html.erb
<h1>Editing Larp</h1>

<%= render 'form', larp: @larp %>

<%= link_to 'Show', @larp %> |
<%= link_to 'Back', larps_path %>

app/views/larps/index.html.erb
<h1>Larps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @larps.each do |larp| %>
      <tr>
        <td><%= larp.name %></td>
        <td><%= larp.short_description %></td>
        <td><%= link_to 'Show', larp %></td>
        <td><%= link_to 'Edit', edit_larp_path(larp) %></td>
        <td><%= link_to 'Destroy', larp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Larp', new_larp_path %>

app/views/larps/new.html.erb
<h1>New Larp</h1>

<%= render 'form', larp: @larp %>

<%= link_to 'Back', larps_path %>

app/views/larps/show.html.erb
<h3> Title: <%= @larp.name %> </h3>

<p> Description: <%= @larp.short_description %> </p>

<%= link_to 'Edit', edit_larp_path(@larp) %> |
<%= link_to 'Back', larps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackDaysLarpWriter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>